sudo: false
dist: trusty
language: node_js
addons:
  chrome: stable
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - export SPEEDRACER_CHROME=google-chrome-stable
cache:
  yarn: true
  directories:
    - node_modules
branches:
  only:
    - master
    - /^greenkeeper-.*$/
notifications:
  email: false
node_js:
  - '6'
after_success: npm run coverage
