sudo: false
language: node_js
before_install:
  - export SPEEDRACER_CHROME=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
cache:
  directories:
    - node_modules
    - chrome-linux
branches:
  only:
    - master
    - /^greenkeeper-.*$/
notifications:
  email: false
node_js:
  - '6'
after_success: npm run coverage
